%% Code Info
% Written by Jordan Middleton 2018
clc;
clear;
close all;

%% Set Variables
prefix = 'MedEdFlynn_';
d_name = 'med_ed_behav.mat'; % Name of master data file
significance = 0.05;
cond1 = 1;
cond2 = 3;
comp = getenv('computername');

if strcmp(comp,'JORDAN-SURFACE') == 1
    master_dir = 'C:\Users\chime\Documents\MATLAB\Data\MedEd';
    beh_dir = 'C:\Users\chime\Documents\MATLAB\Data\MedEd\Behavioral';
    save_dir = 'C:\Users\chime\Documents\MATLAB\MedEd\Export';
    set(0,'DefaultFigurePosition','remove');
elseif strcmp(comp,'OLAV-PATTY') == 1
    master_dir = 'C:\Users\Jordan\Documents\MATLAB\Data\MedEd';
    beh_dir = 'C:\Users\Jordan\Documents\MATLAB\Data\MedEd\Behavioral';
    save_dir = 'C:\Users\Jordan\Documents\MATLAB\MedEd\Export';
    set(0,'DefaultFigurePosition',[1921,45,1280,907]);
end

clear comp

%% Load Variables
cd(master_dir);
load(d_name);

%% Plot Behavioural Data
disp('Plotting behavioral data');
cd(beh_dir);
colors = cbrewer('qual', 'Dark2', 8);
colors = flipud(colors);

f1 = figure('Name','Behavioural',...
    'NumberTitle','off');
for a = 1:3
    if a == 1
        analysis = 'accuracy';
        ylab = 'Accuracy (%)';
        plot_title = 'Accuracy';
        y_lim = [0.5 1];
        y_tick = [0.5 0.6 0.7 0.8 0.9 1.0];
    elseif a == 2
        analysis = 'reactiontime';
        ylab = 'Reaction Time (s)';
        plot_title = 'Reaction Time';
        y_lim = [4 6];
        y_tick = [4.0 4.5 5.0 5.5 6.0];
    elseif a == 3
        analysis = 'confidence';
        ylab = 'Confidence';
        plot_title = 'Confidence';
        y_lim = [5 10];
        y_tick = [5 6 7 8 9 10];
    end
    
    xpos1 = [1 2];
    xpos2 = [1 3];
    xpos3 = [2 3];
    ypos1 = (y_lim(1)+((y_lim(2)-y_lim(1))*0.96));
    ypos2 = (y_lim(1)+((y_lim(2)-y_lim(1))*0.98));
    ypos3 = (y_lim(1)+((y_lim(2)-y_lim(1))*0.94));
    [h,p] = ttest(summary.(analysis).significance.c0,...
        summary.(analysis).significance.c1);
    p01 = p;
    [h,p] = ttest(summary.(analysis).significance.c1,...
        summary.(analysis).significance.c2);
    p12 = p;
    [h,p] = ttest(summary.(analysis).significance.c0,...
        summary.(analysis).significance.c2);
    p02 = p;
    plot_data = transpose(summary.(analysis).plot.mean);
    ci_data = summary.(analysis).ci.within(1,5);
    ci = [ci_data ci_data ci_data];
    
    if p01 < 1e-3
        txt1 = '***';
    elseif p01 < 1e-2
        txt1 = '**';
    elseif p01 < 0.05
        txt1 = '*';
    elseif ~isnan(p01)
        txt1 = 'n.s.';
    end
    
    if p02 < 1e-3
        txt2 = '***';
    elseif p02 < 1e-2
        txt2 = '**';
    elseif p02 < 0.05
        txt2 = '*';
    elseif ~isnan(p02)
        txt2 = 'n.s.';
    end
    
    if p12 < 1e-3
        txt3 = '***';
    elseif p12 < 1e-2
        txt3 = '**';
    elseif p12 < 0.05
        txt3 = '*';
    elseif ~isnan(p12)
        txt3 = 'n.s.';
    end
    
    subplot(1,3,a);
    hold on;
    
    for c = 1:3
        c = bar(c,plot_data(:,c),'FaceColor', colors(c,:));
    end
    
    set(gca,'xtick',[1 2 3],...
        'xticklabel',{'No Conflict','One Conflict','Two Conflict'},...
        'xticklabelrotation',45,...
        'xlim', [0.5 3.5]);
    
    title(plot_title);
    
    ax = gca;
    ax.YLim = y_lim;
    ax.YTick = y_tick;
    ax.FontSize = 12;
    ax.FontName = 'Arial';
    ax.LineWidth = 1.5;
    ax.YLabel.String = ylab;
    ax.FontWeight = 'bold';
    ax.Box = 'off';
    
    e = errorbar(plot_data,ci,'.');
    e.LineWidth = 1.5;
    e.Color = 'k';
    e.MarkerEdgeColor = 'none';
    
    l1 = text(mean(xpos1),...
        ypos1+(ypos1*0.0025),...
        txt1,...
        'horizontalalignment','center',...
        'backgroundcolor','none',...
        'margin',2,...
        'fontsize',8,...
        'fontweight','normal', ...
        'color','k');
    l2 = text(mean(xpos2),...
        ypos2+(ypos1*0.0025),...
        txt2,...
        'horizontalalignment','center',...
        'backgroundcolor','none',...
        'margin',2,...
        'fontsize',8,...
        'fontweight','normal', ...
        'color','k');
    l3 = text(mean(xpos3),...
        ypos3+(ypos1*0.0025),...
        txt3,...
        'horizontalalignment','center',...
        'backgroundcolor','none',...
        'margin',2,...
        'fontsize',8,...
        'fontweight','normal', ...
        'color','k');
    
    s1 = plot(gca,...
        [xpos1(1),xpos1(2)],...
        [ypos1 ypos1],...
        'LineStyle','-',...
        'LineWidth',1.5,...
        'color','k');
    s2 = plot(gca,...
        [xpos2(1),xpos2(2)],...
        [ypos2 ypos2],...
        'LineStyle','-',...
        'LineWidth',1.5,...
        'color','k');
    s3 = plot(gca,...
        [xpos3(1),xpos3(2)],...
        [ypos3 ypos3],...
        'LineStyle','-',...
        'LineWidth',1.5,...
        'color','k');
    
    lab1 = text(2.5,...
        (y_lim(1)+((y_lim(2)-y_lim(1))*0.9)),...
        '*** = p>0.001',...
        'horizontalalignment','left',...
        'backgroundcolor','none',...
        'margin',1,...
        'fontsize',8,...
        'fontweight','normal', ...
        'color','k');
    lab2 = text(2.5,...
        (y_lim(1)+((y_lim(2)-y_lim(1))*0.875)),...
        '** = p>0.01',...
        'horizontalalignment','left',...
        'backgroundcolor','none',...
        'margin',1,...
        'fontsize',8,...
        'fontweight','normal', ...
        'color','k');
    lab3 = text(2.5,...
        (y_lim(1)+((y_lim(2)-y_lim(1))*0.85)),...
        '* = p>0.05',...
        'horizontalalignment','left',...
        'backgroundcolor','none',...
        'margin',1,...
        'fontsize',8,...
        'fontweight','normal', ...
        'color','k');
    lab4 = text(2.5,...
        (y_lim(1)+((y_lim(2)-y_lim(1))*0.825)),...
        'n.s. = not significant',...
        'horizontalalignment','left',...
        'backgroundcolor','none',...
        'margin',1,...
        'fontsize',8,...
        'fontweight','normal', ...
        'color','k');
    
    colormap(colors)
    hold off
end

cd(save_dir);
export_fig(f1,'Behavior','-png');

%% Clean Workspace
clearvars -except summary